version: "3.9"

services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6001:6379"
  
  redis-ui:
    image: redis/redisinsight:latest
    container_name: redis-ui
    restart: unless-stopped
    ports:
      - "6002:5540"
    environment:
      - RI_REDIS_USERNAME=admin
      - RI_REDIS_PASSWORD=admin1234
